### ISSUE TITLE
Questions about the rules in the faq

### ISSUE THREAD

**Issue by a-samsonov-work** [kevquirk/512kb.club#1074]
Hi. I have a some questions:
1. Is it allowed to add sites like the first one in the list (1kb.lejtzen.dev) ? This is a page with one link that leads to the main site with a larger size. Does the rule from the FAQ "Ultra minimal / link pages" not apply here?

2. If the home page contains varying amounts of content (e.g., previews of the first 5 blog articles, which may contain images), can I specify an approximate upper limit for site size?

**Comment by kevquirk** [comment]
Hi @a-samsonov-work,

1. In short, no. That would be classed as a "super minimal" site. There are a number of SM sites on 512KB Club, and we try to review and cull them from time to time, but, like anything, it's finding the time. :-)

2. I couldn't possibly specify a limit as there's too many variables. For example, a site could have thousands on paragraphs of text, with links to many posts/pages, and still be a few hundred KB. Conversely, a page could be a single image that's multiple MB. It's impossible to specify a limit, as each site is built differently. That's why we case each site as it comes.

Hope this helps,

Kev

**Comment by a-samsonov-work** [comment]
Thank you for your answer!
