### ISSUE TITLE
evantravers.com wants to join the club.

### ISSUE THREAD

**Issue by evantravers** [kevquirk/512kb.club#69]
* **Domain name:** evantravers.com
* **GTMetrix results:** https://gtmetrix.com/reports/evantravers.com/blmPzYUv/
* **Uncompressed page size:** 439.7 KB

```
<li>
  <span class="before" style="--data-size:438.8;"></span>
  <span class="after">439.7 KB</span>
  <a class="site" target="blank" href="http://evantravers.com">evantravers.com</a>
</li>
```

**Comment by kevquirk** [comment]
You might want to optimise your avatar image - that's nearly 300kb on its own and it's only renderring @ 36px. It doesn't need to be 600px. I've optimised it for you (72px so it doesn't distort on retina displays).

The image is now 3kb instead of nearly 300kb. You want to replace that and re-test before I add your site to the list? That will probably take you from the blue team to the green team.

New avatar - https://files.kevq.uk/et-avatar.jpg
