### ISSUE TITLE
Sites for review

### ISSUE THREAD

**Issue by korikori** [kevquirk/512kb.club#965]
Blue team
- https://dndd.space/ domain expired/deleted
- https://mousdown.netlify.app/ server error
- https://kaalatrie.github.io/ 404 There isn't a GitHub Pages site here.
- https://lopeztel.xyz/ timeout

Orange team
- http://topik.natenorthway.com/ no DNS record
- https://ethandewey.com/ 404 There isn't a GitHub Pages site here.
- https://0xv31an5a1i5.xyz no DNS record
- https://tjout.com timeout
- https://3000.chat/ no DNS record
- https://ironveil.cloud/ no DNS record
- https://freshnode.net/ PR_END_OF_FILE_ERROR / possible certificate error

Green team
- https://sexiarz.pl/ no DNS record, domain near expiration or in some RGP equivalent 
- https://rmxgrp.dev/ 502 Bad Gateway
- https://julb.es/ "Site not found" by hosting provider
- https://lighthouse16.com/ registrar placeholder page
- https://goestathomas.de/ timeout/certificate issue
- https://c1.fi/v/512kb/about/en/ 404 - Page not found
- https://g.rmxgrp.dev/ This domain is for sale.
- https://www.nurminen.xyz/ You've successfully started the Nginx Proxy Manager.
- https://www.jamontheroad.com/ no DNS record
- https://bruton.tech/ timeout

Conversely, it feels like this check can be automated? The majority of the errors (except for placeholder pages) can be caught easily.

Misc
- https://vfast.co.uk/ is currently at 572KB uncompressed https://gtmetrix.com/reports/vfast.co.uk/DqETnCsd/

**Comment by garritfra** [comment]
Thanks so much for taking the time to go through the list!

I removed most of them via #966, but kept the sites with invalid certs:

* https://lighthouse16.com/
* http://goestathomas.de/

Since they are technically still up, I'm unsure whether we should remove them or not, but I'm open for discussion.

Also, I know that https://lopeztel.xyz/ *should*  still be active. To be sure, I asked the owner in [this](https://fosstodon.org/web/@garritfra/109018393207887007) thread.

Regarding automatic this: I'm sure there's a way to achieve this, but we didn't have the time to implement such a feature yet. I remember that @kmutahar did some effort to add size checking (see [this directory](https://github.com/kevquirk/512kb.club/tree/ec9a0875761dd2bf5f5370f713ac02097e72b202/scripts)). Maybe this could be expanded?

**Comment by garritfra** [comment]
Closing this issue for now, but we can keep the conversation going.

Thanks again for your effort!

**Comment by korikori** [comment]
Not a problem at all, happy to help. I expect that adding such a check should be trivial, but I have no real Python experience - I'll look into @kmutahar's script to see if I can get my head around it.

**Comment by korikori** [comment]
Just a couple of clarifications on the list:
- The problem with https://lighthouse16.com/ is that it opens what appears to be a hosting provider/domain registrar placeholder page;
- My first entry for https://rmxgrp.dev/ should have been for https://kieran.rmxgrp.dev, which is still listed (but also affected).

I've prepared a very simple script that identified 19 of the 21 URLs originally for review, but also has a few false positives. I'll submit a pull request with more details and thoughts shortly.
